// Copic color dataset
// Structure: Dictionary keyed by Family (R, YR, etc.)
// Value: Array of objects { code: 'R01', hex: '#ABCDEF', label: 'Name' }

export const COPIC_FAMILIES = {
    // Red
    R: [
        { code: 'R0000', hex: '#FAEBEB', label: 'Pink Beryl' },
        { code: 'R000', hex: '#F9E5E5', label: 'Cherry White' },
        { code: 'R00', hex: '#F6DCDC', label: 'Pinkish White' },
        { code: 'R01', hex: '#F6D0D0', label: 'Pinkish Vanilla' },
        { code: 'R02', hex: '#F6CACA', label: 'Rose Salmon' },
        { code: 'R05', hex: '#F39D9D', label: 'Salmon Red' },
        { code: 'R08', hex: '#F07575', label: 'Vermilion' },
        { code: 'R11', hex: '#F6D8D0', label: 'Pale Cherry Pink' },
        { code: 'R12', hex: '#F5CCBD', label: 'Light Tea Rose' },
        { code: 'R14', hex: '#F09E96', label: 'Light Rouge' },
        { code: 'R17', hex: '#EC6C5E', label: 'Lipstick Orange' },
        { code: 'R20', hex: '#F5D3D6', label: 'Blush' },
        { code: 'R21', hex: '#F3C5C9', label: 'Sardonyx' },
        { code: 'R22', hex: '#F1B2B7', label: 'Light Prawn' },
        { code: 'R24', hex: '#EB7580', label: 'Prawn' },
        { code: 'R27', hex: '#E74C5B', label: 'Cadmium Red' },
        { code: 'R29', hex: '#E4283C', label: 'Lipstick Red' },
        { code: 'R30', hex: '#F5E1DC', label: 'Pale Yellowish Pink' },
        { code: 'R32', hex: '#F3CEC9', label: 'Peach' },
        { code: 'R35', hex: '#EB857D', label: 'Coral' },
        { code: 'R37', hex: '#E75955', label: 'Carmine' },
        { code: 'R39', hex: '#C23A49', label: 'Garnet' },
        { code: 'R43', hex: '#F099A2', label: 'Bougainvillaea' },
        { code: 'R46', hex: '#E85B6F', label: 'Strong Red' },
        { code: 'R56', hex: '#D9737F', label: 'Currant' },
        { code: 'R59', hex: '#BF4856', label: 'Cardinal' },
        { code: 'R81', hex: '#F2C2D4', label: 'Rose Pink' },
        { code: 'R83', hex: '#EB94B6', label: 'Rose Mist' },
        { code: 'R85', hex: '#DF5E8C', label: 'Rose Red' },
        { code: 'R89', hex: '#9C2542', label: 'Dark Red' }
    ],
    // Yellow Red
    YR: [
        { code: 'YR000', hex: '#FDF1E6', label: 'Silk' },
        { code: 'YR00', hex: '#FBDEC9', label: 'Powder Pink' },
        { code: 'YR01', hex: '#FBD4B9', label: 'Peach Puff' },
        { code: 'YR02', hex: '#F9CAA8', label: 'Light Orange' },
        { code: 'YR04', hex: '#F5AC65', label: 'Chrome Orange' },
        { code: 'YR07', hex: '#F18E31', label: 'Cadmium Orange' },
        { code: 'YR09', hex: '#EB6100', label: 'Chinese Orange' },
        { code: 'YR12', hex: '#F9DDB8', label: 'Loquat' },
        { code: 'YR14', hex: '#F5BE81', label: 'Caramel' },
        { code: 'YR15', hex: '#F3AA59', label: 'Pumpkin Yellow' },
        { code: 'YR16', hex: '#F19531', label: 'Apricot' },
        { code: 'YR18', hex: '#EB690A', label: 'Sanguine' },
        { code: 'YR20', hex: '#F9DDB3', label: 'Yellowish Shade' },
        { code: 'YR21', hex: '#F6C983', label: 'Cream' },
        { code: 'YR23', hex: '#F3AD54', label: 'Yellow Ochre' },
        { code: 'YR24', hex: '#F19932', label: 'Pale Sepia' },
        { code: 'YR27', hex: '#DB8328', label: 'Tuscan Orange' },
        { code: 'YR30', hex: '#FBF2D5', label: 'Macadamia Nut' },
        { code: 'YR31', hex: '#F8DE9D', label: 'Light Reddish Yellow' },
        { code: 'YR61', hex: '#F6D9BF', label: 'Yellowish Skin' },
        { code: 'YR65', hex: '#F1A971', label: 'Atoll' },
        { code: 'YR68', hex: '#EA7C36', label: 'Orange' },
        { code: 'YR82', hex: '#E7B28B', label: 'Mellow Peach' }
    ],
    // Yellow
    Y: [
        { code: 'Y0000', hex: '#FFFFE4', label: 'Yellow Fluorite' },
        { code: 'Y000', hex: '#FEFCD9', label: 'Pale Lemon' },
        { code: 'Y00', hex: '#FEF8B9', label: 'Barium Yellow' },
        { code: 'Y02', hex: '#FDF399', label: 'Canary Yellow' },
        { code: 'Y04', hex: '#FAE946', label: 'Acacia' },
        { code: 'Y06', hex: '#F9E500', label: 'Yellow' },
        { code: 'Y08', hex: '#F8DB00', label: 'Acid Yellow' },
        { code: 'Y11', hex: '#FEF9CC', label: 'Pale Yellow' },
        { code: 'Y13', hex: '#FDF28F', label: 'Lemon Yellow' },
        { code: 'Y15', hex: '#FAE959', label: 'Cadmium Yellow' },
        { code: 'Y17', hex: '#F9DF26', label: 'Golden Yellow' },
        { code: 'Y18', hex: '#F8D62C', label: 'Lightning Yellow' },
        { code: 'Y19', hex: '#F7CD00', label: 'Napoli Yellow' },
        { code: 'Y21', hex: '#FDF0A8', label: 'Buttercup Yellow' },
        { code: 'Y23', hex: '#FBE41A', label: 'Yellowish Beige' },
        { code: 'Y26', hex: '#F4D242', label: 'Mustard' },
        { code: 'Y28', hex: '#DAB866', label: 'Lionet Gold' },
        { code: 'Y32', hex: '#FBEBBD', label: 'Cashmere' },
        { code: 'Y35', hex: '#F8D26C', label: 'Maize' },
        { code: 'Y38', hex: '#F6C142', label: 'Honey' }
    ],
    // Yellow Green
    YG: [
        { code: 'YG0000', hex: '#F4FBEB', label: 'Lily White' },
        { code: 'YG00', hex: '#EAF6D5', label: 'Mimosa Yellow' },
        { code: 'YG01', hex: '#DDF1B8', label: 'Green Bice' },
        { code: 'YG03', hex: '#CFEB9D', label: 'Yellow Green' },
        { code: 'YG05', hex: '#C2E585', label: 'Salad' },
        { code: 'YG06', hex: '#B5DF73', label: 'Yellowish Green' },
        { code: 'YG07', hex: '#9FD852', label: 'Acid Green' },
        { code: 'YG09', hex: '#87C82B', label: 'Lettuce Green' },
        { code: 'YG11', hex: '#E2F1CF', label: 'Mignonette' },
        { code: 'YG13', hex: '#D2E9A7', label: 'Chartreuse' },
        { code: 'YG17', hex: '#9BCE5D', label: 'Grass Green' },
        { code: 'YG21', hex: '#E8F3C7', label: 'Anise' },
        { code: 'YG23', hex: '#D9ECAB', label: 'New Leaf' },
        { code: 'YG25', hex: '#C0DD82', label: 'Celadon Green' },
        { code: 'YG41', hex: '#D3E7BD', label: 'Pale Cobalt Green' },
        { code: 'YG45', hex: '#B8D993', label: 'Cobalt Green' },
        { code: 'YG61', hex: '#CCE2C2', label: 'Pale Moss' },
        { code: 'YG63', hex: '#B2D0A4', label: 'Pea Green' },
        { code: 'YG67', hex: '#8CBA7A', label: 'Moss' },
        { code: 'YG91', hex: '#DEDCC0', label: 'Putty' },
        { code: 'YG93', hex: '#D1CC89', label: 'Grayish Yellow' },
        { code: 'YG95', hex: '#C5BB4E', label: 'Pale Olive' },
        { code: 'YG97', hex: '#9E942D', label: 'Spanish Olive' },
        { code: 'YG99', hex: '#6D6E26', label: 'Marine Green' }
    ],
    // Green
    G: [
        { code: 'G0000', hex: '#F1F9F6', label: 'Crystal Opal' },
        { code: 'G000', hex: '#E5F6EE', label: 'Pale Green' },
        { code: 'G00', hex: '#D2EFE2', label: 'Jade Green' },
        { code: 'G02', hex: '#C3EAD6', label: 'Spectrum Green' },
        { code: 'G03', hex: '#B3E4CB', label: 'Meadow Green' },
        { code: 'G05', hex: '#97DAAD', label: 'Emerald Green' },
        { code: 'G07', hex: '#77CF90', label: 'Nile Green' },
        { code: 'G09', hex: '#5AC376', label: 'Veronese Green' },
        { code: 'G12', hex: '#D9EEDC', label: 'Sea Green' },
        { code: 'G14', hex: '#B8E2BE', label: 'Apple Green' },
        { code: 'G16', hex: '#8FD5A2', label: 'Malachite' },
        { code: 'G17', hex: '#63C67C', label: 'Forest Green' },
        { code: 'G19', hex: '#26B254', label: 'Bright Parrot Green' },
        { code: 'G20', hex: '#E8F5D8', label: 'Wax White' },
        { code: 'G21', hex: '#D9EFCA', label: 'Lime Green' },
        { code: 'G24', hex: '#C2E4B0', label: 'Willow' },
        { code: 'G28', hex: '#00974E', label: 'Ocean Green' },
        { code: 'G29', hex: '#007A38', label: 'Pine Tree Green' },
        { code: 'G40', hex: '#E4F4DC', label: 'Dim Green' },
        { code: 'G43', hex: '#CDEBC0', label: 'Pistachio' },
        { code: 'G46', hex: '#9BD684', label: 'Mistletoe' },
        { code: 'G82', hex: '#C5DCAA', label: 'Spring Dim Green' },
        { code: 'G85', hex: '#9AC980', label: 'Verdigris' },
        { code: 'G94', hex: '#9CAE87', label: 'Grayish Olive' },
        { code: 'G99', hex: '#5E7444', label: 'Olive' }
    ],
    // Blue Green
    BG: [
        { code: 'BG0000', hex: '#EAF8FA', label: 'Snow Green' },
        { code: 'BG000', hex: '#DDF4F5', label: 'Pale Aqua' },
        { code: 'BG01', hex: '#CBEFEF', label: 'Aqua Blue' },
        { code: 'BG02', hex: '#B9E8E8', label: 'New Blue' },
        { code: 'BG05', hex: '#8CDADA', label: 'Holiday Blue' },
        { code: 'BG07', hex: '#5BC8C8', label: 'Petroleum Blue' },
        { code: 'BG09', hex: '#00B0B0', label: 'Blue Green' },
        { code: 'BG10', hex: '#E0F0F1', label: 'Cool Shadow' },
        { code: 'BG11', hex: '#D1EAEF', label: 'Moon White' },
        { code: 'BG13', hex: '#B7DEE3', label: 'Mint Green' },
        { code: 'BG15', hex: '#91CED7', label: 'Aqua' },
        { code: 'BG18', hex: '#51B4C0', label: 'Teal Blue' },
        { code: 'BG23', hex: '#BDDFD7', label: 'Coral Sea' },
        { code: 'BG32', hex: '#BCE2DD', label: 'Aqua Mint' },
        { code: 'BG34', hex: '#A3D7D1', label: 'Horizon Green' },
        { code: 'BG45', hex: '#A0D8D7', label: 'Nile Blue' },
        { code: 'BG49', hex: '#54C4C2', label: 'Duck Blue' },
        { code: 'BG53', hex: '#A9D6DE', label: 'Ice Mint' },
        { code: 'BG57', hex: '#77C1CC', label: 'Jasper' },
        { code: 'BG70', hex: '#D9E9E5', label: 'Ocean Mist' },
        { code: 'BG72', hex: '#A8D2CB', label: 'Ice Ocean' },
        { code: 'BG75', hex: '#6EB7AA', label: 'Abyss Green' },
        { code: 'BG78', hex: '#409C8E', label: 'Bronze' },
        { code: 'BG90', hex: '#E2E6E2', label: 'Gray Sky' },
        { code: 'BG93', hex: '#C9D5CD', label: 'Green Gray' },
        { code: 'BG96', hex: '#93B0A5', label: 'Bush' },
        { code: 'BG99', hex: '#5F8578', label: 'Flagstone Blue' }
    ],
    // Blue
    B: [
        { code: 'B0000', hex: '#EBF5FC', label: 'Pale Porcelain Blue' },
        { code: 'B000', hex: '#E0F0F9', label: 'Pale Porcelain' },
        { code: 'B00', hex: '#D4EBF6', label: 'Frost Blue' },
        { code: 'B01', hex: '#C9E5F2', label: 'Mint Blue' },
        { code: 'B02', hex: '#A9D8EE', label: 'Robin’s Egg Blue' },
        { code: 'B04', hex: '#7AC5E5', label: 'Tahitian Blue' },
        { code: 'B05', hex: '#5BBBE1', label: 'Process Blue' },
        { code: 'B06', hex: '#34AADC', label: 'Peacock Blue' },
        { code: 'B12', hex: '#C6E3F4', label: 'Ice Blue' },
        { code: 'B14', hex: '#99CCE8', label: 'Light Blue' },
        { code: 'B16', hex: '#61B0DE', label: 'Cyanine Blue' },
        { code: 'B18', hex: '#2A92CA', label: 'Lapis Lazuli' },
        { code: 'B21', hex: '#E0ECF6', label: 'Baby Blue' },
        { code: 'B23', hex: '#B5D5E9', label: 'Phthalo Blue' },
        { code: 'B24', hex: '#9AC9E4', label: 'Sky' },
        { code: 'B26', hex: '#6FAFD6', label: 'Cobalt Blue' },
        { code: 'B28', hex: '#4289BD', label: 'Royal Blue' },
        { code: 'B29', hex: '#2272A9', label: 'Ultramarine' },
        { code: 'B32', hex: '#D3E6EF', label: 'Pale Blue' },
        { code: 'B34', hex: '#9DC5D8', label: 'Manganese Blue' },
        { code: 'B37', hex: '#5898BC', label: 'Antwerp Blue' },
        { code: 'B39', hex: '#2B7098', label: 'Prussian Blue' },
        { code: 'B41', hex: '#DDF0F8', label: 'Powder Blue' },
        { code: 'B45', hex: '#93CEEA', label: 'Smoky Blue' },
        { code: 'B52', hex: '#BAD5E4', label: 'Soft Greenish Blue' },
        { code: 'B60', hex: '#E1E6F3', label: 'Pale Hydrangea' },
        { code: 'B63', hex: '#BBC8E2', label: 'Light Hydrangea' },
        { code: 'B66', hex: '#8B9FC9', label: 'Clematis' },
        { code: 'B69', hex: '#5070AE', label: 'Stratospheric Blue' },
        { code: 'B79', hex: '#374F87', label: 'Iris' },
        { code: 'B91', hex: '#E5E9EC', label: 'Pale Grayish Blue' },
        { code: 'B93', hex: '#C3D0DA', label: 'Light Crockery Blue' },
        { code: 'B95', hex: '#92ABCD', label: 'Light Grayish Cobalt' },
        { code: 'B97', hex: '#6382A7', label: 'Night Blue' },
        { code: 'B99', hex: '#36567C', label: 'Agate' }
    ],
    // Blue Violet
    BV: [
        { code: 'BV0000', hex: '#EFEBF5', label: 'Pale Thistle' },
        { code: 'BV000', hex: '#E4DEEF', label: 'Iridescent Mauve' },
        { code: 'BV00', hex: '#DAD4E9', label: 'Mauve Shadow' },
        { code: 'BV01', hex: '#CCC4E3', label: 'Viola' },
        { code: 'BV02', hex: '#BDB3DC', label: 'Prune' },
        { code: 'BV04', hex: '#9F90CD', label: 'Blue Berry' },
        { code: 'BV08', hex: '#7762AB', label: 'Blue Violet' },
        { code: 'BV11', hex: '#E1D9EB', label: 'Soft Violet' },
        { code: 'BV13', hex: '#C8BBDC', label: 'Hydrangea Blue' },
        { code: 'BV17', hex: '#8B7CBD', label: 'Deep Reddish Blue' },
        { code: 'BV20', hex: '#E5E3EB', label: 'Dull Lavender' },
        { code: 'BV23', hex: '#C4C2D8', label: 'Grayish Lavender' },
        { code: 'BV25', hex: '#A3A0C8', label: 'Grayish Violet' },
        { code: 'BV29', hex: '#585381', label: 'Slate' },
        { code: 'BV31', hex: '#EBEBF4', label: 'Pale Lavender' },
        { code: 'BV34', hex: '#DEDEE8', label: 'Lavender' }
    ],
    // Violet
    V: [
        { code: 'V000', hex: '#F9E5F2', label: 'Pale Heath' },
        { code: 'V01', hex: '#F3D2E3', label: 'Heath' },
        { code: 'V04', hex: '#EAA9CB', label: 'Lilac' },
        { code: 'V05', hex: '#E594C1', label: 'Azalea' },
        { code: 'V06', hex: '#DF7CB6', label: 'Lavender' },
        { code: 'V09', hex: '#D2559C', label: 'Violet' },
        { code: 'V12', hex: '#F0D4E5', label: 'Pale Lilac' },
        { code: 'V15', hex: '#DEAECB', label: 'Mallow' },
        { code: 'V17', hex: '#CD86AF', label: 'Amethyst' },
        { code: 'V20', hex: '#F3E3EA', label: 'Wistaria' },
        { code: 'V22', hex: '#EACFD8', label: 'Ash Lavender' },
        { code: 'V25', hex: '#DCA9BD', label: 'Pale Blackberry' },
        { code: 'V28', hex: '#CF84A3', label: 'Eggplant' },
        { code: 'V91', hex: '#E8DEDF', label: 'Pale Grape' },
        { code: 'V93', hex: '#D6C4C8', label: 'Early Grape' },
        { code: 'V95', hex: '#BA9DA6', label: 'Light Grape' },
        { code: 'V99', hex: '#7F5A66', label: 'Aubergine' }
    ],
    // Red Violet
    RV: [
        { code: 'RV0000', hex: '#F9EBEF', label: 'Evening Primrose' },
        { code: 'RV000', hex: '#F8DEE5', label: 'Pale Purple' },
        { code: 'RV00', hex: '#F5CBD8', label: 'Water Lily' },
        { code: 'RV02', hex: '#F0BAD2', label: 'Sugared Almond Pink' },
        { code: 'RV04', hex: '#ED97BB', label: 'Shocking Pink' },
        { code: 'RV06', hex: '#E974A8', label: 'Cerise' },
        { code: 'RV09', hex: '#D44A8C', label: 'Fuchsia' },
        { code: 'RV10', hex: '#F9E1E7', label: 'Pale Pink' },
        { code: 'RV11', hex: '#F6CDD9', label: 'Pink' },
        { code: 'RV13', hex: '#F1A8C0', label: 'Tender Pink' },
        { code: 'RV14', hex: '#EC8BAE', label: 'Begonia Pink' },
        { code: 'RV17', hex: '#E46797', label: 'Deep Magenta' },
        { code: 'RV19', hex: '#D14882', label: 'Red Violet' },
        { code: 'RV21', hex: '#F8D7DD', label: 'Light Pink' },
        { code: 'RV23', hex: '#F3B7C2', label: 'Pure Pink' },
        { code: 'RV25', hex: '#EC93A5', label: 'Dog Rose Flower' },
        { code: 'RV29', hex: '#DA5172', label: 'Crimson' },
        { code: 'RV32', hex: '#F4D4D0', label: 'Shadow Pink' },
        { code: 'RV34', hex: '#ECB6B0', label: 'Dark Pink' },
        { code: 'RV42', hex: '#F3CFCB', label: 'Salmon Pink' },
        { code: 'RV52', hex: '#EFC9CC', label: 'Cotton Candy' },
        { code: 'RV55', hex: '#E6A3A9', label: 'Hollyhock' },
        { code: 'RV63', hex: '#D9AAB1', label: 'Begonia' },
        { code: 'RV66', hex: '#C2737F', label: 'Raspberry' },
        { code: 'RV69', hex: '#974C5B', label: 'Peony' },
        { code: 'RV91', hex: '#EADCDD', label: 'Grayish Cherry' },
        { code: 'RV93', hex: '#DDBFC2', label: 'Smoky Purple' },
        { code: 'RV95', hex: '#CC9CA2', label: 'Baby Blossoms' },
        { code: 'RV99', hex: '#875B62', label: 'Argyle Purple' }
    ],
    // Earth / Browns
    E: [
        { code: 'E0000', hex: '#FEF8F3', label: 'Floral White' },
        { code: 'E000', hex: '#FDF1E5', label: 'Pale Fruit Pink' },
        { code: 'E00', hex: '#FCECDD', label: 'Cotton Pearl' },
        { code: 'E01', hex: '#FBE6D6', label: 'Pink Flamingo' },
        { code: 'E02', hex: '#F9DFCE', label: 'Fruit Pink' },
        { code: 'E04', hex: '#E9C7C8', label: 'Lipstick Natural' },
        { code: 'E07', hex: '#CC938A', label: 'Light Mahogany' },
        { code: 'E08', hex: '#C47E69', label: 'Brown' },
        { code: 'E09', hex: '#B8654E', label: 'Burnt Sienna' },
        { code: 'E11', hex: '#F9E2C8', label: 'Barley Beige' },
        { code: 'E13', hex: '#F5CEAC', label: 'Light Suntan' },
        { code: 'E15', hex: '#ECBA8D', label: 'Dark Suntan' },
        { code: 'E17', hex: '#C98F70', label: 'Reddish Brass' },
        { code: 'E18', hex: '#A3684B', label: 'Copper' },
        { code: 'E19', hex: '#95583B', label: 'Redwood' },
        { code: 'E21', hex: '#FBE8CC', label: 'Soft Sun' },
        { code: 'E23', hex: '#F5D6AF', label: 'Hazelnut' },
        { code: 'E25', hex: '#E4BF92', label: 'Caribe Cocoa' },
        { code: 'E27', hex: '#C6A580', label: 'Africano' },
        { code: 'E29', hex: '#A8855F', label: 'Burnt Umber' },
        { code: 'E30', hex: '#FBF5DE', label: 'Bisque' },
        { code: 'E31', hex: '#F8ECCE', label: 'Brick Beige' },
        { code: 'E33', hex: '#F4D8B1', label: 'Sand' },
        { code: 'E34', hex: '#EFD1A6', label: 'Toast' },
        { code: 'E35', hex: '#ECD09E', label: 'Chamois' },
        { code: 'E37', hex: '#CDA86F', label: 'Sepia' },
        { code: 'E39', hex: '#B98F56', label: 'Leather' },
        { code: 'E40', hex: '#F7F3EB', label: 'Brick White' },
        { code: 'E41', hex: '#F4EEE5', label: 'Pearl White' },
        { code: 'E42', hex: '#E9DFC9', label: 'Sand White' },
        { code: 'E43', hex: '#DED3B3', label: 'Dull Ivory' },
        { code: 'E44', hex: '#C9BE9E', label: 'Clay' },
        { code: 'E47', hex: '#AFA487', label: 'Dark Brown' },
        { code: 'E49', hex: '#877B5E', label: 'Dark Bark' },
        { code: 'E50', hex: '#F9F1E5', label: 'Egg Shell' },
        { code: 'E51', hex: '#F7EBD5', label: 'Milky White' },
        { code: 'E53', hex: '#F3E1BF', label: 'Raw Silk' },
        { code: 'E55', hex: '#EBCB9B', label: 'Light Camel' },
        { code: 'E57', hex: '#CEAC79', label: 'Light Walnut' },
        { code: 'E59', hex: '#B6955D', label: 'Walnut' },
        { code: 'E70', hex: '#EFEDE4', label: 'Ash Rose' },
        { code: 'E71', hex: '#DED7C6', label: 'Champagne' },
        { code: 'E74', hex: '#B6A696', label: 'Cocoa Brown' },
        { code: 'E77', hex: '#9E8B78', label: 'Maroon' },
        { code: 'E79', hex: '#77624F', label: 'Cashew' }
    ],
    // Cool Grays
    C: [
        { code: 'C0', hex: '#F2F4F5', label: 'Cool Gray No.0' },
        { code: 'C1', hex: '#EBEFF0', label: 'Cool Gray No.1' },
        { code: 'C2', hex: '#E0E5E7', label: 'Cool Gray No.2' },
        { code: 'C3', hex: '#D5DADD', label: 'Cool Gray No.3' },
        { code: 'C4', hex: '#C2C8CB', label: 'Cool Gray No.4' },
        { code: 'C5', hex: '#AFB6B9', label: 'Cool Gray No.5' },
        { code: 'C6', hex: '#9DA4A8', label: 'Cool Gray No.6' },
        { code: 'C7', hex: '#8B9396', label: 'Cool Gray No.7' },
        { code: 'C8', hex: '#777D80', label: 'Cool Gray No.8' },
        { code: 'C9', hex: '#656A6D', label: 'Cool Gray No.9' },
        { code: 'C10', hex: '#535759', label: 'Cool Gray No.10' }
    ],
    // Neutral Grays
    N: [
        { code: 'N0', hex: '#F5F5F5', label: 'Neutral Gray No.0' },
        { code: 'N1', hex: '#EDEDED', label: 'Neutral Gray No.1' },
        { code: 'N2', hex: '#E5E5E5', label: 'Neutral Gray No.2' },
        { code: 'N3', hex: '#DBDBDB', label: 'Neutral Gray No.3' },
        { code: 'N4', hex: '#CCCCCC', label: 'Neutral Gray No.4' },
        { code: 'N5', hex: '#BDBDBD', label: 'Neutral Gray No.5' },
        { code: 'N6', hex: '#ACACAC', label: 'Neutral Gray No.6' },
        { code: 'N7', hex: '#999999', label: 'Neutral Gray No.7' },
        { code: 'N8', hex: '#858585', label: 'Neutral Gray No.8' },
        { code: 'N9', hex: '#737373', label: 'Neutral Gray No.9' },
        { code: 'N10', hex: '#606060', label: 'Neutral Gray No.10' }
    ],
    // Toner Grays
    T: [
        { code: 'T0', hex: '#F5F5F5', label: 'Toner Gray No.0' },
        { code: 'T1', hex: '#EDEDED', label: 'Toner Gray No.1' },
        { code: 'T2', hex: '#E5E5E5', label: 'Toner Gray No.2' },
        { code: 'T3', hex: '#DBDBDB', label: 'Toner Gray No.3' },
        { code: 'T4', hex: '#CCCCCC', label: 'Toner Gray No.4' },
        { code: 'T5', hex: '#BDBDBD', label: 'Toner Gray No.5' },
        { code: 'T6', hex: '#ACACAC', label: 'Toner Gray No.6' },
        { code: 'T7', hex: '#999999', label: 'Toner Gray No.7' },
        { code: 'T8', hex: '#858585', label: 'Toner Gray No.8' },
        { code: 'T9', hex: '#737373', label: 'Toner Gray No.9' },
        { code: 'T10', hex: '#606060', label: 'Toner Gray No.10' }
    ],
    // Warm Grays
    W: [
        { code: 'W0', hex: '#F6F5F4', label: 'Warm Gray No.0' },
        { code: 'W1', hex: '#F0EFED', label: 'Warm Gray No.1' },
        { code: 'W2', hex: '#E7E6E4', label: 'Warm Gray No.2' },
        { code: 'W3', hex: '#DEDDDB', label: 'Warm Gray No.3' },
        { code: 'W4', hex: '#D0CFCB', label: 'Warm Gray No.4' },
        { code: 'W5', hex: '#C2C0BD', label: 'Warm Gray No.5' },
        { code: 'W6', hex: '#B0AFAF', label: 'Warm Gray No.6' },
        { code: 'W7', hex: '#9E9C9A', label: 'Warm Gray No.7' },
        { code: 'W8', hex: '#8B8987', label: 'Warm Gray No.8' },
        { code: 'W9', hex: '#777574', label: 'Warm Gray No.9' },
        { code: 'W10', hex: '#656362', label: 'Warm Gray No.10' }
    ],
    // Black
    Special: [
        { code: '100', hex: '#000000', label: 'Black' },
        { code: '110', hex: '#1C0D13', label: 'Special Black' },
        { code: '0', hex: '#FFFFFF', label: 'Colorless Blender' }
    ]
};
